### ISSUE TITLE
Show history of changes in metadata

### ISSUE THREAD

**Issue by brockfanning** [worldbank/sdg-metadata#16]
We need to figure out a way to display the changes to an indicator's metadata in a human-friendly way. The ideal solution would actually display a "diff" with strike-throughs, etc.

Some thoughts on a possible solution:

* During build process, loop through each indicator
* Loop through each change (in the Git history) to that file
* Look at two adjacent changes at once - A vs B
* Convert A and B both to javascript objects
* Loop through the fields in the objects
* If a difference is found, do a diff (library that can generate a rich HTML diff?)
* Save each difference found in a list, containing language, commit, date, field, indicator, and rich diff (anything else)
* Write the results to a json file
* Use this data on the front-end to display the diffs in some way

**Comment by JenPark9** [comment]
Some policy-level solutions we could consider in the interim (which may be
related to this proposal):
- flag at the indicator level with an "Updated DATE" icon
and
- flag at the indicator's metadata concept level with an "Updated DATE"
icon.
Then, add a metadata concept for "Description of metadata changes" that can
hold a running list of changes, perhaps taken from the IAEG-SDG spreadsheet.
At the country level, even this solution would be an improvement over the
current system.

**Comment by brockfanning** [comment]
@JenPark9 I've got some screenshots to illustrate a possible approach and how this might look, for your review and feedback:

Indicator page - showing the way that users will get to the history page:


![sdg-metadata-history-1](https://user-images.githubusercontent.com/1319083/99151134-0e663b80-2667-11eb-9847-df641b816500.png)

After the user clicks the "Source history" button:


![sdg-metadata-history-2](https://user-images.githubusercontent.com/1319083/99151138-19b96700-2667-11eb-895c-6563d1529d1f.png)

After the user clicks the "Comparison" button:


![sdg-metadata-history-3](https://user-images.githubusercontent.com/1319083/99151146-2e95fa80-2667-11eb-8654-66257e5f95de.png)

After the user clicks the "Raw changes" button:


![sdg-metadata-history-4](https://user-images.githubusercontent.com/1319083/99151151-38b7f900-2667-11eb-8561-e0af3efed536.png)

After the user clicks the "Github" button:


![sdg-metadata-history-5](https://user-images.githubusercontent.com/1319083/99151203-73ba2c80-2667-11eb-9a9a-89fcb268e929.png)

**Comment by JenPark9** [comment]
Thank you! Will do!
Can you advise about how to remove uppercase indicator files in github? Do
I just move them to a new folder for deletion?

**Comment by JenPark9** [comment]
Hi Brock,
I think this is off to a great start. I'm attaching a file with
questions/comments for you. Could you provide a mock up showing an update
to the Data source string for comparison purposes? As I understand it, the
comparison tab is meant for countries and agencies, including maybe UNSD.
The raw changes tab is meant for us or UNSD on behalf of countries and
agencies. The github tab is meant for us to modify the current version of
the metadata file.

**Comment by brockfanning** [comment]
@JenPark9 I don't think the attachment made it to me, since it was a Github notification email. You'll need to either post it here or send it to my address in a separate email.

Those 3 buttons are for different audiences, I guess:
* Comparison: Most non-technical users who just want to see the content changes
* Raw changes: Translators and anyone who wants to see -- in more detail -- exactly what changed, at the markup level. This can also be useful in cases where it is not obvious in "Comparison" what changed.
* Github: Just something I threw in - this is a link to the "commit" in Github in which the indicator changed. It's not particularly informative and could be removed. I thought it might be helpful but I don't have a real use-case in mind.

I'll try screenshots of another indicator that has more clear changes.

**Comment by brockfanning** [comment]
This feature was deployed so I will close the issue (though more discussion is needed for phase 3 of the project, and I'll open a separate issue for that).
