### ISSUE TITLE
Consider switching to GatsbyJS

### ISSUE THREAD

**Issue by brockfanning** [worldbank/sdg-metadata#27]
Although Jekyll (and the Minimal Mistakes theme) is working great, we may want to consider switching to GatsbyJS for the sole reason of making everything run with Node.js. As we try to make this project more re-usable, it would make users' lives easier if they only have to install Node.js, instead of Node.js and Ruby. It would also remove an extra language that developers who want to customize the code would need to learn.

**Comment by JenPark9** [comment]
What would be the estimated lift in time and effort to make the switch?
Would existing translations and files be affected?

**Comment by brockfanning** [comment]
A bit of background: Right now we're using the static-site generator _Jekyll_, which requires the programming language _Ruby_. In order to make our site look nice, we're using the Jekyll theme _Minimal Mistakes_.

If we wanted to remove the Ruby requirement, we could switch to a static-site generator which runs on Node.js (which is the programming language that the rest of this project is written in, such as the automated imports, PDF generation, etc.). The most popular such static-site generator is called GatsbyJS.

As for estimates for the various tasks - I would break it down something like this:

1. Implementing a basic site with Gatsby: between 10-15 hours
2. Making it look nice - for this part, there are two options:
    1. Switching to a ready-made GatsbyJS theme ([here is a gallery of GatsbyJS themes](https://themejam.gatsbyjs.org/showcase)). This would mean that the look-and-feel of the website would change, but would be very easy. About 4-6 hours.
    2. Writing custom styling to replicate what we have with Jekyll's "Minimal Mistakes" theme. This would mean that the site will keep the look-and-feel that we're accustomed to, but it would take a lot longer. Probably another 10-15 hours.

Either way, nothing would need to change in regards to the navigation of the site, the API endpoints, or the translations themselves.

**Comment by brockfanning** [comment]
With limited funding there are a lot of other tasks that are more important than this one. And since I opened this, I'll go ahead and close.
