### ISSUE TITLE
Indicator updates and in-progress translations

### ISSUE THREAD

**Issue by brockfanning** [worldbank/sdg-metadata#50]
Right now, when an indicator is updated via the Word template, the English source changes will only be used by new translations. But translations that are already in progress will not get the updated English source. Do we want the in-progress translations to automatically get updated English source? Or do we want there to be a separate optional script to run, which pulls the latest English source into in-progress translations?

**Comment by JenPark9** [comment]
the latter.

**Comment by JenPark9** [comment]
I'm sorry. The former. An automatic script.

**Comment by JenPark9** [comment]
1, right now, pdfs are not available for ENG files. Is that because the
contract is pending? I get a 404 message.
2. Uploaded indicators in github do not seem to automatically populate in
weblate. Am I missing something?

**Comment by brockfanning** [comment]
1. I'm not sure why that happened. Is it working now? This is something to keep an eye on.
2. Yes, that's partly what this issue was about. It's different depending on whether it's a new indicator or an update to an indicator that's already in progress:
    * New indicators: A manual step is needed in Weblate to pull it in. I can look into whether that can be automated.
    * In-progress translation: We're going to need to add some code so that in-progress translations get updated. (That's what this issue is about.) We would need to confirm that Weblate correctly detects that the source has changed, and flags the necessary translations as needing to be re-translated.

**Comment by JenPark9** [comment]
1. I'm not sure why that happened. Is it working now? This is something
   to keep an eye on.

YES, WORKING NOW. MUST HAVE BEEN A DELAY OF SOME SORT.


   1. Yes, that's partly what this issue was about. It's different
   depending on whether it's a new indicator or an update to an indicator
   that's already in progress:
      - New indicators: A manual step is needed in Weblate to pull it in. I
      can look into whether that can be automated.

OK, IN THE INTERIM, I NEED TO BE ABLE TO DO THE MANUAL STEP SO THAT i CAN
DESCRIBE IT TO BUYANT, ETC. POSSIBLE FOR YOU TO POINT ME IN THAT DIRECTION.
FOR PHASE 2, YES, I THINK WE WANT THIS TO BE AUTOMATED IF POSSIBLE.


   1.
      - In-progress translation: We're going to need to add some code so
      that in-progress translations get updated. (That's what this issue is
      about.) We would need to confirm that Weblate correctly detects that the
      source has changed, and flags the necessary translations as needing to be
      re-translated.
      - SO THAT I UNDERSTAND, WOULD ALEXANDER BE SEEING THE "OLD" ENG FILES
      IN WEBLATE RIGHT NOW, OR THE "NEW" FILES. IF HE IS ONLY SEEING THE OLD
      ONES, I THINK WE NEED TO GET PERMISSION FROM BUYANT TO MAKE THIS CHANGE
      ASAP. I GUESS i AM NOT UNDERSTANDING WHAT IN PROGRESS MEANS--ANYTHING
      TRANSLATED IN WEBLATE, OR ANYTHING NOT FINISHED TRANSLATING IN WEBLATE?

**Comment by brockfanning** [comment]
Regarding the manual step in Weblate - I'm hopeful that Weblate will do it for us, maybe every 24 hours. Let's give it a day and see how it goes?

I've done the manual setup necessary so that Alexander sees the latest English source. However the ones uploaded today will not show yet. See my note above about waiting a day.

By "in progress" I mean that the translator has already performed some translations in Weblate.

**Comment by brockfanning** [comment]
@JenPark9 FYI, I just made an edit in Weblate to reflect the updated Github location. It looks like 5-3-1 and 3-2-1 are both in Weblate now, without me doing anything. I'm not sure if it happened at the moment I made that unrelated change, or if it did just happen automatically, with a delay. I guess we can see again for the next time.

**Comment by brockfanning** [comment]
@JenPark9 There's potential for a quick fix thanks to Weblate specifically - which has this feature: https://docs.weblate.org/en/latest/admin/addons.html#update-po-files-to-match-pot-msgmerge

This needs to be turned on per component (indicator). I've just turned it on for 1-1-1a, as a test. If you know of an indicator that needs updated source, we could use that as another test. Just let me know which indicator, and I'll enable this feature. Then you can upload the updated Word template, and we'll see how it goes.

**Comment by JenPark9** [comment]
this fix would be for an indicator where the eng version needs a formatting
change (so that the translation could receive that formatting change)?
Then we should turn on 1.1.1b, 4.1.1bc, 5.3.1, 5.3.2 6.4.1. in weblate.
But I haven't fixed the Eng versions yet.
So then, after we turn this feature on in weblate, we would reload those
corrected eng templates into the indicator folder on the master? would that
generate automatically a pull to weblate for those files?

**Comment by brockfanning** [comment]
@JenPark9 Ok, why don't we start with 1.1.1b only? I've just enabled this feature for 1.1.1b. So, yes, you would upload the changed Word template to master, generate the automatic PR, and then we'd see how it goes.

**Comment by JenPark9** [comment]
ok, the formatting change I made to 1.1.1b was to remove bullets from the
references. I merged to master. let me know what you see

**Comment by brockfanning** [comment]
I went into to Weblate's "repository maintenance" page and pressed "Commit" (because it said there were "uncommitted changes") and then and I pressed "Pull" to pull in the latest changes from GitHub. Here is the result for the OTHER_DOC field in 1.1.1b: https://hosted.weblate.org/translate/sdg-metadata/1-1-1b/ru/?q=state%3A%3Ctranslated&offset=8

Relevant observations:
* It appears to be set to "Needs editing"
* The English source doesn't have any bullets (`<li>` tags)
* The Russian translation is still there, and still has the bullets
* There are a lot of warning messages on the right side, like "mismatching line breaks" and "XML markup"

All of that seems like good news to me. We've updated the English source for an "in-progress" translation, and maintained the connection from the current translation. And Weblate is correctly flagging the field as needing an edit, and pointing out problems. And we didn't have to write any code. :)

**Comment by brockfanning** [comment]
@JenPark9 If you are happy with the results, I can enable this feature for all the other indicators too - just let me know.

**Comment by JenPark9** [comment]
:)
So, how do we remove the bullets in the Russian and French versions? Is
this something we need to do as a "guest translator" in weblate?

**Comment by JenPark9** [comment]
Yes, this solves one part of the problem: changes to make to ENG files.
But it doesn't yet address formatting changes to translated files...

**Comment by brockfanning** [comment]
I don't think there is any way around the fact that the translations are going to need to be re-done, when this happens. If it's a simple enough change, it's possible a non-speaker can do it, but otherwise a translator is going to have to re-do the translation. This solution is nice because it appears to maintain the connection between the old translation and the new source, which is great. But there's always going to have to be a manual re-translation, afterwards. For this reason, changing the English source is something we generally don't want to do unless absolutely necessary.

**Comment by JenPark9** [comment]
So, if these are formatting issues only, then can I attempt to make the
change in weblate myself? Like bullets, header font?
Also, I think I need to go into webkate anyway to cut and paste the image
in 4.1.1 so that the Ru and fr render correctly, right?

**Comment by brockfanning** [comment]
Yes, if it's clear to you what needs to change, even though you don't speak Russian, you could conceivably make the change. For example, if the English source changed an `<h1>` to an `<h2>`, you can certainly make this change without needing to know Russian, assuming you can locate the correct `<h1>` in the translation. Similarly, if the URL of a link is being updated, that's something you can surely do without needing to speak the language.

Also just to re-iterate - I'll need to turn on this feature for each indicator before you can start uploading updates.

**Comment by JenPark9** [comment]
OK,
1) for formatting changes that I would like to make to the ENG file (that
has a corresponding translation), I want to activate 4.1.1bc, 5.3.1, 5.3.2,
and 6.4.1.
2) for formatting issues (like bold for entire paragraphs)  that seem to
have occurred only in the RUS file, what should I do? I think this is the
'mangled code' issue.
3) for images that were mangled in RUS and FRE, can I just make the change
to the translated file in weblate? An example is 4.1.1bc.

**Comment by brockfanning** [comment]
1. I've enabled this for 4.1.1bc and 5.3.1. It looks like 5.3.2 and 6.4.1 are not yet "components" in Weblate. That, I think, is something we'll need to write a little code for, and I'll work on that.
2. That's the thing we're going to do locally, using a search/replace.
3. Yes, sounds good.

**Comment by JenPark9** [comment]
Hi Brock,

English:
Ok, 4.1.1bc and 5.3.1 (ENG formatting updates) are done.
I would like to also activate 11.1.1 and 17.3.1 for the same.

For awareness, I have finished templates and formatting QC using the
authoring tool for phases 1-2D. I finished templates for phases 2E and 2F.
I will finish QC for those phases today. All of the prepared templates are
in the preview site.

Then, we have phase G as the last set of tier 1 indicators to make
templates and QC That will be about 105 indicators/115 metadata files.

Translations:
I am eager to work on the code you shared with me to correct formatting
issues in RUS and FRE. I will do that later today and tomorrow.

**Comment by JenPark9** [comment]
Hi Brock,
I am trying to activate 11.1.1 in weblate to allow it to receive an updated
.po file. I get as far as going  to Manage, but I don't see an option for
Addons. This is what I see. Do I need to download something? I should be
signed in to Weblate...
Thanks!
[image: image.png]

**Comment by brockfanning** [comment]
Regarding the ability to turn on the "update po files to match pot" functionality, I think that is just a permissions issue in Weblate, which we can resolve there. I'd just need to know your Weblate username.

FYI, I've just merged a code change that should help Weblate automatically create "components" for newly-created indicators. So I believe it is now OK to upload new indicators, whenever you'd like. When the automatic PR is created, it will include blank translation files for each language.

**Comment by brockfanning** [comment]
This is obsolete now that we're using the "monolingual" approach in Weblate.
