### ISSUE TITLE
Pre-populate translations of goal, target and indicator names (when available)?

### ISSUE THREAD

**Issue by JenPark9** [worldbank/sdg-metadata#71]
These are available from the UN for the official 6 languages. Can we pre-populate the metadata files with them, when available? Would this be through the glossary feature in Weblate?

**Comment by brockfanning** [comment]
One way to do this would be to write a script that creates translation files for every indicator, in all 6 languages, and populates those 3 fields based on what we can get from the UN source.

**Comment by JenPark9** [comment]
This would also support pre-population of "Related indicators" in MSD concept 0.f.

**Comment by JenPark9** [comment]
If we try it, we would need to try it for RUS only first, then maybe FRE once that relationship is solid.

**Comment by JenPark9** [comment]
And also names of custodian agencies (0.g, 3.f)
And translations of MSD concept names

**Comment by JenPark9** [comment]
This was requested by STATCAN on May 6th.

**Comment by brockfanning** [comment]
We created a one-time script to import official titles, and ran it, so I think we can close this.
