### ISSUE TITLE
pre-populate authoring template with iaeg-sdg formatted metadata

### ISSUE THREAD

**Issue by JenPark9** [worldbank/sdg-metadata#72]
using our formatting map,  
[SDG_Metadata_Authoring_Tool__Word_v2.1.docx](https://github.com/worldbank/sdg-metadata/files/4575946/SDG_Metadata_Authoring_Tool__Word_v2.1.docx)
could a script be written to:

1. search for defined headers in iaeg-sdg format and insert that text into authoring template; and
2. apply standard formatting to those fields

for subsequent review/quality check by human editor before uploading into weblate?

**Comment by JenPark9** [comment]
[IAEG format to Word.docx](https://github.com/worldbank/sdg-metadata/files/4575992/IAEG.format.to.Word.docx)

Step by step instructions for parsing script to follow (in human language)

**Comment by brockfanning** [comment]
Creating or editing a Word file with a script is a really tough problem. You'll recall when we tried it once before, and decided that it was not good enough. I can imagine this would be a great feature, to avoid the massive manual work of getting all the indicators into the authoring tool. My first suspicion though is that it would not be possible. But I will think on it more. It may also be possible to do something else, which makes the job easier, but doesn't actually create/update the Word files - for example, by creating some simple text files that are easier to copy/paste into the authoring tool.

**Comment by JenPark9** [comment]
righto. Will continue to think of other aspects of the MR creation/formatting process that we might be able to streamline--for this project or the next related one.

**Comment by brockfanning** [comment]
An updated on this - we've discussed the possibility that template could have an "Import SDMX" button, which would take an SDMX file and populate the fields according to whatever metadata was in that file. This is similar to what is proposed here, though the source would need to be in SDMX format first.

**Comment by brockfanning** [comment]
Another update: The idea of an "Import SDMX" button was a good one, but turns out to be technically nearly impossible, mostly because of the more complete HTML that is generated, like footnotes and (soon) math equations. Also phase 3 will make this obsolete, I believe, so I'll go ahead and close.
