### ISSUE TITLE
Find a way to post/file on github populated ENG templates for sharing/updating

### ISSUE THREAD

**Issue by JenPark9** [worldbank/sdg-metadata#74]
So that custodian agencies can update quickly when submitting for approval to UNSD, and then for to upload for any updates to translation.

**Comment by JenPark9** [comment]
Maybe something like this--not sure. And we provide instructions for when to use the template (for revisions, for example)
![image](https://user-images.githubusercontent.com/20671658/81098565-89d87a80-8ed7-11ea-9084-dc6b85ab8aca.png)

**Comment by brockfanning** [comment]
@JenPark9 This would depend on being able to dynamically generate the Word templates from scratch, which is pretty much impossible technically (mostly because of footnotes) or at least extremely difficult. I'll go ahead and close this but feel free to re-open if needed.

**Comment by JenPark9** [comment]
agree to close
