### ISSUE TITLE
Organize indicators by goal and flag "new" postings

### ISSUE THREAD

**Issue by JenPark9** [worldbank/sdg-metadata#80]
This could be by goal icon, if desirable. It could also follow the NRP/Open SDGs branding of arraying indicator metadata if of interest (thermometer of metadata, files available for translating, and files translated.
It should consider number of languages featured, and plan for 3-6.
This is not an immediate issue, but if the next contract is awarded, it will be an important issue to reduce translator and user fatigue.

**Comment by brockfanning** [comment]
@JenPark9 Here are a couple of mockups for possible approaches here:

Dropdown filters:

![indicator-filters-dropdowns](https://user-images.githubusercontent.com/1319083/100278187-77389800-2f32-11eb-9731-9a9523cb8adc.png)

Sidebar filters:

![indicator-filters-sidebar](https://user-images.githubusercontent.com/1319083/100278213-80c20000-2f32-11eb-83d8-160c9a140ed3.png)

One gotcha with the sidebar filters is that the list of targets is very long.

**Comment by brockfanning** [comment]
@JenPark9 Also here's a mockup showing how it would look if the language pages became simply a list of the 17 goal icons.

![indicator-filters-icons](https://user-images.githubusercontent.com/1319083/100297762-6b160000-2f5d-11eb-8e8b-32969ec67dbf.png)

**Comment by JenPark9** [comment]
I love this mock up!

**Comment by brockfanning** [comment]
@JenPark9 Following up on that approach then, I assume that clicking a goal icon should take the user to a goal page, listing targets, which take users to target pages. Here are examples:

Goal page:

![goal-page](https://user-images.githubusercontent.com/1319083/100411169-f7e4ba80-303e-11eb-8e49-4ff7e2472c9b.png)

Target page:

![target-page](https://user-images.githubusercontent.com/1319083/100411183-0337e600-303f-11eb-93f0-0aa7e47013ba.png)

**Comment by JenPark9** [comment]
From the goal page, can you get icons for the targets? I can check w
Statistics Sweden on this--i think they worked to have the target icons
made. Back to you on that soon.
Re the target page--yes, I think the listing of indicators is great. Would
we have 1 indicator button for more than 2 indicator metadata file?

**Comment by JenPark9** [comment]
https://www.globalgoals.org/resources
For the target icons...

**Comment by brockfanning** [comment]
> From the goal page, can you get icons for the targets?

@JenPark9 Thanks for the link to the globalgoal.org resources. One issue there is that they only have English target icons. Would you be OK with displaying English target icons even on non-English pages?

> Would we have 1 indicator button for more than 2 indicator metadata file?

Can you clarify that question or give an example? I'm not sure what you're asking.

**Comment by JenPark9** [comment]
I am getting the other languages for the targets. I have a source for
french.... :)
An example for 1 indicator with 2 metadata files is 1.1.1a, and 1.1.1.b.
Both correspond to indicator 1.1.1.

**Comment by JenPark9** [comment]
Switzerland will give me the link for FRE... working on the others.
Probably ECLAC has SPA...not sure if ECE has RUS but will check...

**Comment by brockfanning** [comment]
About the 1 indicator with 2 files question - are you saying that, on the "1.1" target page, you'd like there to be a "1.1.1" button that takes the user to another page with 2 buttons, "1.1.1a" and "1.1.1b"?

**Comment by JenPark9** [comment]
No, just wondering how we will display that. No particular ideas. :)

**Comment by brockfanning** [comment]
Ok gotcha. I was assuming that we would not change anything in that regard - it would continue to be 2 separate buttons, "1.1.1a" and "1.1.1b".

**Comment by JenPark9** [comment]
Ok!

**Comment by brockfanning** [comment]
@JenPark9 I've fixed the sorting order of the targets/indicators, so for example 2.2.2a will appear before 2.2.3. This is up now in the preview folder.

**Comment by JenPark9** [comment]
I think this looks great. Can we push to the master?

**Comment by brockfanning** [comment]
Sure - the whole thing? History buttons and all the navigational changes?

**Comment by JenPark9** [comment]
not history buttons yet. probably not until phase 3 for that.
re goals and targets, have you/CODE heard back from Buyant? I gave her a
demo earlier this week in the context of another meeting, and I think she
was ok with it, but I think she is waiting to receive something directly
from CODE via invoice?

**Comment by brockfanning** [comment]
Not yet - ok great I'll merge those navigational changes.
